# Generated by Django 2.2.3 on 2019-07-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('level_of_study', models.CharField(choices=[(None, ''), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Prefer not to disclose', 'Prefer not to disclose')], max_length=30)),
                ('graduation_year', models.CharField(choices=[(None, ''), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024 or later', '2024 or later'), ('Prefer not to disclose', 'Prefer not to disclose')], default='', max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(None, ''), ('Female', 'Female'), ('Male', 'Male'), ('Other (Please Specify)', 'Other (Please Specify)')], max_length=30)),
                ('gender_other', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('race', models.CharField(choices=[(None, ''), ('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Asian/Pacific Islander', 'Asian/Pacific Islander'), ('Black or African American', 'Black or African American'), ('Hispanic', 'Hispanic'), ('White/Caucasian', 'White/Caucasian'), ('Multiple ethnicity/Other (Please Specify)', 'Multiple ethnicity/Other (Please Specify)'), ('Prefer not to diclose', 'Prefer not to disclose')], default='', max_length=45)),
                ('race_other', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=13)),
                ('shirt_size', models.CharField(choices=[(None, ''), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=3)),
                ('dietary_restrictions', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('additional_link', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.CharField(default='', max_length=50)),
                ('learn_or_gain', models.TextField(default='', max_length=1000)),
                ('resume', models.URLField(blank=True, default='', max_length=500)),
                ('conduct_box', models.BooleanField(default=False)),
                ('share_box', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ucr.MyUser')),
            ],
        ),
    ]
