# Generated by Django 2.2.3 on 2019-07-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0003_auto_20190720_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='email address'),
        ),
    ]
